export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST'
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS'
export const BRAND_LIST_FAIL = 'BRAND_LIST_FAIL'

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'
export const SAVE_BRAND_REQUEST = ' SAVE_BRAND_REQUEST'
export const  SAVE_BRAND_FAIL = ' SAVE_BRAND_FAIL'


export const BRAND_LIST_PRODUCTS_REQUEST = 'BRAND_LIST_PRODUCTS_REQUEST'
export const BRAND_LIST_PRODUCTS_SUCCESS = 'BRAND_LIST_PRODUCTS_SUCCESS'
export const BRAND_LIST_PRODUCTS_FAIL = 'BRAND_LIST_PRODUCTS_FAIL'

export const CATE_LIST_PRODUCTS_REQUEST = 'CATE_LIST_PRODUCTS_REQUEST'
export const CATE_LIST_PRODUCTS_SUCCESS = 'CATE_LIST_PRODUCTS_SUCCESS'
export const CATE_LIST_PRODUCTS_FAIL = 'CATE_LIST_PRODUCTS_FAIL'

export const CREATE_BRAND_REQUEST = 'CREATE_BRAND_REQUEST'
export const CREATE_BRAND_SUCCESS = 'CREATE_BRAND_SUCCESS'
export const CREATE_BRAND_FAIL = 'CREATE_BRAND_FAIL'

export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL'

export const DELETE_BRAND_REQUEST = 'DELETE_BRAND_REQUEST'
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS'
export const DELETE_BRAND_FAIL = 'DELETE_BRAND_FAIL'

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL'
