export const RES_CREATE_REQUEST = 'RES_CREATE_REQUEST'
export const RES_CREATE_SUCCESS = 'RES_CREATE_SUCCESS'
export const RES_CREATE_FAIL = 'RES_CREATE_FAIL'

export const TABLE_REQUEST = "TABLE_REQUEST"
export const TABLE_SUCCESS = "TABLE_SUCCESS"
export const TABLE_FAIL = "TABLE_FAIL"
